
DROP TABLE "FACTTABLE";
DROP TABLE "PRODUCT";
DROP TABLE "CUSTOMER";
DROP TABLE "SUPPLIER";
DROP TABLE "STORE";
DROP TABLE "DATETABLE";
 
CREATE TABLE "PRODUCT" (
  "PRODUCT_ID" VARCHAR2(6) NOT NULL, 
  "PRODUCT_NAME" VARCHAR2(30) NOT NULL, 
   CONSTRAINT PRODUCTS_PK PRIMARY KEY (PRODUCT_ID));
   
   CREATE TABLE "CUSTOMER" (
  "CUSTOMER_ID" VARCHAR2(4) NOT NULL, 
  "CUSTOMER_NAME" VARCHAR2(30) NOT NULL, 
   CONSTRAINT CUSTOMER_PK PRIMARY KEY ("CUSTOMER_ID"));
   
   CREATE TABLE "STORE" (
  "STORE_ID" VARCHAR2(4) NOT NULL, 
  "STORE_NAME" VARCHAR2(20) NOT NULL, 
   CONSTRAINT STORE_PK PRIMARY KEY ("STORE_ID"));
   
   CREATE TABLE "SUPPLIER" (
  "SUPPLIER_ID" VARCHAR2(5) NOT NULL, 
  "SUPPLIER_NAME" VARCHAR2(30) NOT NULL, 
   CONSTRAINT SUPPLIER_PK PRIMARY KEY ("SUPPLIER_ID"));

CREATE TABLE "DATETABLE"
  (
    T_DATE DATE NOT NULL, 
    T_YEAR    NUMBER(10,0),
    T_QUARTER NUMBER(10,0),
    T_MONTH  CHAR(10 BYTE),
    T_DAY   NUMBER(10,0),
    CONSTRAINT DATETABLE_pk PRIMARY KEY (T_DATE));
    

    CREATE TABLE "FACTTABLE" (
      "TRANSACTION_ID" NUMBER(8,0) PRIMARY KEY,
      "PRODUCT_ID" VARCHAR2(6) NOT NULL,
      "CUSTOMER_ID" VARCHAR2(4) NOT NULL,
      "STORE_ID" VARCHAR2(4) NOT NULL, 
      "SUPPLIER_ID" VARCHAR2(5) NOT NULL, 
      "T_DATE" DATE, 
      "QUANTITY" NUMBER(3,0) NOT NULL,
      "TOTALSALES" NUMBER(5,2) NOT NULL,
      "PRICE" NUMBER(5,2) DEFAULT (0.0) NOT NULL,
      
      CONSTRAINT fk_PRODUCT
      FOREIGN KEY (PRODUCT_ID)
      REFERENCES "PRODUCT"(PRODUCT_ID),
      
      CONSTRAINT fk_CUSTOMER
      FOREIGN KEY (CUSTOMER_ID)
      REFERENCES "CUSTOMER"(CUSTOMER_ID),
      
      CONSTRAINT fk_STORE
      FOREIGN KEY (STORE_ID)
      REFERENCES "STORE"(STORE_ID),
      
      CONSTRAINT fk_SUPPLIER
      FOREIGN KEY (SUPPLIER_ID)
      REFERENCES "SUPPLIER"(SUPPLIER_ID),
      
      CONSTRAINT fk_DATETABLE
      FOREIGN KEY (T_DATE)
      REFERENCES "DATETABLE"(T_DATE));
      
--      alter table "FACTTABLE" add constraint DATE_fk
--      foreign key (T_DATE)
--      references  "DATE"(T_DATE);
 


   
   